### ISSUE TITLE
Doesnt work anymore?

### ISSUE THREAD

**Issue by ottelo9** [l1m3r/freeVHUSB4SL#2]
The free client on the host pc not showing my steam link :(

**Comment by l1m3r** [comment]
Still working fine for me (had to setup my dusty SLink and so on...).
Let me be blunt: If you do/try nothing to solve this I won't (and can't) help you.

OSs, Network, whats working, download vhusbarmserver manually, just imagine what information the other side might need to help you solve the issue.

https://standalone-sysadmin.com/how-to-ask-questions-on-the-internet-3c77062c831c
https://www.wikihow.com/Ask-a-Question-on-the-Internet-and-Get-It-Answered

**Comment by ottelo9** [comment]
Hey thanks for your answer + sorry for the noob question ^^ I was too lazy.
Ok what I've done:

- Steam Link is up2date, connected via WiFi 5GHz
- Moonlight is working fine
- I previously installed virtualherefreeinstaller, I removed the folder inside the app folder, so I think its deinstalled?
- installed VHUSB4SL on my steamlink - fVHusb.tgz on stick - (app is visible). I suppose "install" means steam link simply copies the content of the tar to the app folder?
- do a power cycle and start VHUSB4SL (click on the icon -> black screen -> connecting -> back to home screen)
- start the [virtualhere client software](https://virtualhere.com/sites/default/files/usbclient/vhui64.exe) (not installed as service) on my Host PC (Win10, LAN)
- cannot find the VHUSB4SL instance on my steam link :(

I checked if your app downloads the arm binaries to bin folder-> ok! vhusbdarm inside bin folder is the same that I can download from the web page! Maybe you have an older one that works???


--EDIT--
OK after I fully reset my steamlink and installed VHUSB it works!!!!!! I simply power down SL and start VHUSB app (closes automatically). Then I start the client on my host PC -> automatically found SL !! Thanks!

**Comment by l1m3r** [comment]
Great, any Idea what was the problem?
I assume your SLink and computer are on the same logical/physical network?
VHUSB uses [Bonjour](https://en.wikipedia.org/wiki/Bonjour_(software)) to automatically find a connection between server & client - maybe Windows needed a restart to get it working properly?

**Comment by ottelo9** [comment]
I think the problem was the previously installed VirtualHereFreeInstaller or something else.
